In [1]:
# import libraries
import pandas as pd
import numpy as np  
from IPython.display import display
import json

In [2]:
# load fr_tracking csv
csv1 = 'fr_tracking.csv'

fr_tracking0 = pd.read_csv(csv1, encoding="ISO-8859-1", sep=None, engine="python", header=0)
display(fr_tracking0.head(5))

,publication_date,effective_on,department,agency,independent_reg_agency,title,abstract,action,citation,document_number,regulation_id_number,docket_number,significant,econ_significant,3(f)(1) significant,Major,html_url,Notes,5 U.S.C. 804(2).
0,2/1/21,4/2/21,Securities and Exchange Commission,NaN,NaN,Exemption From the Definition of ÃClearing Ag...,The Securities and Exchange Commission (ÃComm...,Final rule.,86 FR 7637,2020-28194,3235-AK74,NaN,.,.,NaN,0,https://www.federalregister.gov/documents/2021...,NaN,NaN
1,2/1/21,2/1/21,Government Ethics Office,NaN,NaN,2021 Civil Monetary Penalties Inflation Adjust...,In accordance with the Federal Civil Penalties...,Final rule.,86 FR 7635,2021-00714,3209-AA55,NaN,0,0,NaN,.,https://www.federalregister.gov/documents/2021...,NaN,NaN
2,2/1/21,2/1/21,Interior Department,Office of the Secretary,NaN,Civil Penalties Inflation Adjustments,This rule revises U.S. Department of the Inter...,Final rule.,86 FR 7653,2021-01303,1024-AE67,NaN,0,0,NaN,0,https://www.federalregister.gov/documents/2021...,NaN,NaN
3,2/1/21,2/1/21,Interior Department,National Indian Gaming Commission,NaN,Annual Adjustment of Civil Monetary Penalty To...,In compliance with the Federal Civil Penalties...,Final rule.,86 FR 7646,2021-01413,.,NaN,0,0,NaN,0,https://www.federalregister.gov/documents/2021...,No RIN number.,NaN
4,2/1/21,3/3/21,Homeland Security Department,Coast Guard,NaN,"Anchorage; Galveston Harbor, Bolivar Roads Cha...",The Coast Guard is establishing a 48-hour time...,Final rule.,86 FR 7647,2021-02000,1625-AA01,NaN,0,0,NaN,.,https://www.federalregister.gov/documents/2021...,NaN,NaN

In [3]:
# load gao_cra json
json_file = "gao_cra.json"

with open(json_file, "r", encoding="ISO-8859-1") as f:
    data = json.load(f) 
    
gao_cra0 = pd.DataFrame(data["results"])

display(gao_cra0.head(5))
gao_cra0.to_csv("gao_cra.csv", index=False)

,url,title,agency,subagency,type,description,priority,date_published_in_federal_register,effective,received,control_number,fed_reg_number,identifier,major_rule_report
0,https://www.gao.gov/fedrules/210969,Federal Rules: Energy Conservation Program: En...,Department of Energy,Department of Energy,Major,ENERGY CONSERVATION PROGRAM: ENERGY CONSERVATI...,Significant/Substantive,2025-01-21T13:00:00Z,2025-03-24T13:00:00Z,2025-01-30T13:00:00Z,210969,90 FR 7464,1904-AD82,https://www.gao.gov/products/b-337132
1,https://www.gao.gov/fedrules/210873,Federal Rules: Minimum Standards For Driver?S ...,Department of Homeland Security,Transportation Security Administration,Major,MINIMUM STANDARDS FOR DRIVER?S LICENSES AND ID...,Significant/Substantive,2025-01-14T13:00:00Z,2025-01-14T13:00:00Z,2025-01-22T13:00:00Z,210873,90 FR 3472,1652-AA77,https://www.gao.gov/products/b-337041
2,https://www.gao.gov/fedrules/210892,Federal Rules: Certificates Of Compliance | U....,Independent Government Entities,Consumer Product Safety Commission,Major,CERTIFICATES OF COMPLIANCE,Significant/Substantive,2025-01-08T13:00:00Z,2026-07-08T13:00:00Z,2025-01-21T13:00:00Z,210892,90 FR 1800,NaN,https://www.gao.gov/products/b-337029
3,https://www.gao.gov/fedrules/210874,"Federal Rules: Post-9/11 Improvements, Fry Sch...",Department of Veterans Affairs,Department of Veterans Affairs,Major,"POST-9/11 IMPROVEMENTS, FRY SCHOLARSHIP, AND I...",Significant/Substantive,2025-01-16T13:00:00Z,2025-03-17T13:00:00Z,2025-01-17T13:00:00Z,210874,90 FR 5324,2900-AQ88,https://www.gao.gov/products/b-337024
4,https://www.gao.gov/fedrules/210824,Federal Rules: Securing The Information And Co...,Department of Commerce,Bureau of Industry and Security,Major,SECURING THE INFORMATION AND COMMUNICATIONS TE...,Significant/Substantive,2025-01-16T13:00:00Z,2025-03-17T13:00:00Z,2025-01-16T13:00:00Z,210824,90 FR 5360,0694-AJ56,https://www.gao.gov/products/b-337023

In [4]:
# fr_tracking df info
print("fr_tracking0 info:")
fr_tracking0.info()

fr_tracking0 info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12893 entries, 0 to 12892
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   publication_date        12893 non-null  object
 1   effective_on            12799 non-null  object
 2   department              12887 non-null  object
 3   agency                  8915 non-null   object
 4   independent_reg_agency  3508 non-null   float64
 5   title                   12890 non-null  object
 6   abstract                12800 non-null  object
 7   action                  12848 non-null  object
 8   citation                12892 non-null  object
 9   document_number         12893 non-null  object
 10  regulation_id_number    12855 non-null  object
 11  docket_number           10762 non-null  object
 12  significant             12879 non-null  object
 13  econ_significant        12879 non-null  object
 14  3(f)(1) significant     5908 non-null   object
 15  Major                   12866 non-null  object
 16  html_url                12892 non-null  object
 17  Notes                   1154 non-null   object
 18  5 U.S.C. 804(2).        0 non-null      float64
dtypes: float64(2), object(17)
memory usage: 1.9+ MB

In [5]:
# gao_cra df info
print("gao_cra0 info:")
gao_cra0.info()

gao_cra0 info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7399 entries, 0 to 7398
Data columns (total 14 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   url                                 7399 non-null   object
 1   title                               7399 non-null   object
 2   agency                              7399 non-null   object
 3   subagency                           7378 non-null   object
 4   type                                7399 non-null   object
 5   description                         7399 non-null   object
 6   priority                            7260 non-null   object
 7   date_published_in_federal_register  7184 non-null   object
 8   effective                           7292 non-null   object
 9   received                            7399 non-null   object
 10  control_number                      7399 non-null   object
 11  fed_reg_number                      7357 non-null   object
 12  identifier                          5311 non-null   object
 13  major_rule_report                   459 non-null    object
dtypes: object(14)
memory usage: 809.4+ KB

In [6]:
# fr_tracking data manipulation

# change date columns to YYYY-MM-DD format
fr_date_cols = ["publication_date", "effective_on"]
fr_tracking0[fr_date_cols] = fr_tracking0[fr_date_cols].apply(pd.to_datetime, errors="coerce", format="mixed")

# change id columns to string
fr_id_cols = ["citation", "regulation_id_number"]
fr_tracking0[fr_id_cols] = fr_tracking0[fr_id_cols].astype("string")

display(fr_tracking0.head(2))

,publication_date,effective_on,department,agency,independent_reg_agency,title,abstract,action,citation,document_number,regulation_id_number,docket_number,significant,econ_significant,3(f)(1) significant,Major,html_url,Notes,5 U.S.C. 804(2).
0,2021-02-01,2021-04-02,Securities and Exchange Commission,NaN,NaN,Exemption From the Definition of ÃClearing Ag...,The Securities and Exchange Commission (ÃComm...,Final rule.,86 FR 7637,2020-28194,3235-AK74,NaN,.,.,NaN,0,https://www.federalregister.gov/documents/2021...,NaN,NaN
1,2021-02-01,2021-02-01,Government Ethics Office,NaN,NaN,2021 Civil Monetary Penalties Inflation Adjust...,In accordance with the Federal Civil Penalties...,Final rule.,86 FR 7635,2021-00714,3209-AA55,NaN,0,0,NaN,.,https://www.federalregister.gov/documents/2021...,NaN,NaN

In [7]:
print("fr_tracking0 info:")
fr_tracking0.info()

fr_tracking0 info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12893 entries, 0 to 12892
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   publication_date        12893 non-null  datetime64[ns]
 1   effective_on            12734 non-null  datetime64[ns]
 2   department              12887 non-null  object
 3   agency                  8915 non-null   object
 4   independent_reg_agency  3508 non-null   float64
 5   title                   12890 non-null  object
 6   abstract                12800 non-null  object
 7   action                  12848 non-null  object
 8   citation                12892 non-null  string
 9   document_number         12893 non-null  object
 10  regulation_id_number    12855 non-null  string
 11  docket_number           10762 non-null  object
 12  significant             12879 non-null  object
 13  econ_significant        12879 non-null  object
 14  3(f)(1) significant     5908 non-null   object
 15  Major                   12866 non-null  object
 16  html_url                12892 non-null  object
 17  Notes                   1154 non-null   object
 18  5 U.S.C. 804(2).        0 non-null      float64
dtypes: datetime64[ns](2), float64(2), object(13), string(2)
memory usage: 1.9+ MB

In [8]:
# gao_cra data manipulation

# change date columns to YYYY-MM-DD format
gao_date_cols = ["date_published_in_federal_register", "effective", "received"]
gao_cra0[gao_date_cols] = gao_cra0[gao_date_cols].apply(pd.to_datetime, errors="coerce")
gao_cra0[gao_date_cols] = gao_cra0[gao_date_cols].apply(lambda x: x.dt.tz_localize(None).dt.normalize())

# change id columns to string
gao_id_cols = ["fed_reg_number", "identifier"]
gao_cra0[gao_id_cols] = gao_cra0[gao_id_cols].astype("string")

display(gao_cra0.head(2))

,url,title,agency,subagency,type,description,priority,date_published_in_federal_register,effective,received,control_number,fed_reg_number,identifier,major_rule_report
0,https://www.gao.gov/fedrules/210969,Federal Rules: Energy Conservation Program: En...,Department of Energy,Department of Energy,Major,ENERGY CONSERVATION PROGRAM: ENERGY CONSERVATI...,Significant/Substantive,2025-01-21,2025-03-24,2025-01-30,210969,90 FR 7464,1904-AD82,https://www.gao.gov/products/b-337132
1,https://www.gao.gov/fedrules/210873,Federal Rules: Minimum Standards For Driver?S ...,Department of Homeland Security,Transportation Security Administration,Major,MINIMUM STANDARDS FOR DRIVER?S LICENSES AND ID...,Significant/Substantive,2025-01-14,2025-01-14,2025-01-22,210873,90 FR 3472,1652-AA77,https://www.gao.gov/products/b-337041

In [9]:
print("gao_cra0 info:")
gao_cra0.info()

gao_cra0 info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7399 entries, 0 to 7398
Data columns (total 14 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   url                                 7399 non-null   object
 1   title                               7399 non-null   object
 2   agency                              7399 non-null   object
 3   subagency                           7378 non-null   object
 4   type                                7399 non-null   object
 5   description                         7399 non-null   object
 6   priority                            7260 non-null   object
 7   date_published_in_federal_register  7031 non-null   datetime64[ns]
 8   effective                           7253 non-null   datetime64[ns]
 9   received                            7399 non-null   datetime64[ns]
 10  control_number                      7399 non-null   object
 11  fed_reg_number                      7357 non-null   string
 12  identifier                          5311 non-null   string
 13  major_rule_report                   459 non-null    object
dtypes: datetime64[ns](3), object(9), string(2)
memory usage: 809.4+ KB

In [10]:
# fr_tracking data cleaning

# drop rows with "N/A" or no values in the citation column
fr_tracking_all_fr_cit = fr_tracking0.replace("N/A", np.nan).dropna(subset=["citation"])

# only keep rows that contain "FR" plus numbers (eleminates abnormalities)
fr_tracking_all_fr_cit = fr_tracking_all_fr_cit[fr_tracking_all_fr_cit["citation"].str.fullmatch(r".*\bFR\b.*", na=False)]

In [11]:
# gao_cra data cleaning

# drop rows with "N/A" or no values in the fed_reg_number column
gao_cra_all_fr_cit = gao_cra0.replace("N/A", np.nan).dropna(subset=["fed_reg_number"])

# only keep rows that contain "FR" plus numbers (eleminates abnormalities)
gao_cra_all_fr_cit = gao_cra_all_fr_cit[gao_cra_all_fr_cit["fed_reg_number"].str.fullmatch(r".*\bFR\b.*", na=False)]

In [12]:
# fr_tracking anti-join on citation/fed_reg_number
fr_tracking_unmatched_on_fr_cit = fr_tracking_all_fr_cit[~fr_tracking_all_fr_cit["citation"].isin(gao_cra_all_fr_cit["fed_reg_number"])]
fr_tracking_unmatched_on_fr_cit.info()
fr_tracking_unmatched_on_fr_cit.to_csv("fr_tracking_unmatched_on_fr_cit.csv", index=False)

<class 'pandas.core.frame.DataFrame'>
Index: 6913 entries, 0 to 12892
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   publication_date        6913 non-null   datetime64[ns]
 1   effective_on            6781 non-null   datetime64[ns]
 2   department              6907 non-null   object
 3   agency                  4816 non-null   object
 4   independent_reg_agency  2754 non-null   float64
 5   title                   6911 non-null   object
 6   abstract                6847 non-null   object
 7   action                  6878 non-null   object
 8   citation                6913 non-null   string
 9   document_number         6913 non-null   object
 10  regulation_id_number    6887 non-null   string
 11  docket_number           5750 non-null   object
 12  significant             6905 non-null   object
 13  econ_significant        6907 non-null   object
 14  3(f)(1) significant     3552 non-null   object
 15  Major                   6894 non-null   object
 16  html_url                6912 non-null   object
 17  Notes                   506 non-null    object
 18  5 U.S.C. 804(2).        0 non-null      float64
dtypes: datetime64[ns](2), float64(2), object(13), string(2)
memory usage: 1.1+ MB

In [13]:
# gao_cra anti-join on citation/fed_reg_number
gao_cra_unmatched_on_fr_cit = gao_cra_all_fr_cit[~gao_cra_all_fr_cit["fed_reg_number"].isin(fr_tracking_all_fr_cit["citation"])]
gao_cra_unmatched_on_fr_cit.info()
gao_cra_unmatched_on_fr_cit.to_csv("gao_cra_unmatched_on_fr_cit.csv", index=False)

<class 'pandas.core.frame.DataFrame'>
Index: 1209 entries, 41 to 7385
Data columns (total 14 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   url                                 1209 non-null   object
 1   title                               1209 non-null   object
 2   agency                              1209 non-null   object
 3   subagency                           1197 non-null   object
 4   type                                1209 non-null   object
 5   description                         1209 non-null   object
 6   priority                            1206 non-null   object
 7   date_published_in_federal_register  1209 non-null   datetime64[ns]
 8   effective                           1187 non-null   datetime64[ns]
 9   received                            1209 non-null   datetime64[ns]
 10  control_number                      1209 non-null   object
 11  fed_reg_number                      1209 non-null   string
 12  identifier                          893 non-null    string
 13  major_rule_report                   66 non-null     object
dtypes: datetime64[ns](3), object(9), string(2)
memory usage: 141.7+ KB

In [14]:
# fr_tracking data cleaning

# drop rows with "." or no values in the regulation_id_number column
fr_tracking_all_id_date = fr_tracking0.replace(".", np.nan).dropna(subset=["regulation_id_number"])

# drop rows containing "Docket No", "Doc. No.", or "FR"
fr_tracking_all_id_date = fr_tracking_all_id_date[~fr_tracking_all_id_date["regulation_id_number"].str.contains(r"Docket No|Doc\. No\.|FR", na=False, regex=True)]

# convert regulation_id_number column to a list of lists (so groups of RINs can be searched for individual RINs)
fr_tracking_all_id_date["regulation_id_number"] = fr_tracking_all_id_date["regulation_id_number"].str.split(r"\s*;\s*")

In [15]:
# gao_cra data cleaning (CONTINUE WORKING HERE)

# drop rows with "N/A" no values in the identifier column
gao_cra_all_id_date = gao_cra0.replace("N/A", np.nan).dropna(subset=["identifier"])

#gao_cra_all_id_date.to_csv("gao_cra_all_id_date.csv", index=False)

In [16]:
# fr_tracking anti-join on BOTH RIN and pub date
# unmatched_fr_tracking2 = fr_tracking0.merge(
#     gao_cra0,
#     left_on=["regulation_id_number", "publication_date"],
#     right_on=["identifier", "date_published_in_federal_register"],
#     how="left",
#     indicator=True
# ).query('_merge == "left_only"').drop(columns=["_merge"])

# unmatched_fr_tracking2.info()
#unmatched_fr_tracking2.to_csv("unmatched_fr_tracking2.csv", index=False)

In [17]:
# gao_cra anti-join on BOTH RIN and pub date
# unmatched_gao_cra2 = gao_cra0.merge(
#     fr_tracking0,
#     left_on=["identifier", "date_published_in_federal_register"],
#     right_on=["regulation_id_number", "publication_date"],
#     how="left",
#     indicator=True
# ).query('_merge == "left_only"').drop(columns=["_merge"])

# unmatched_gao_cra2.info()
#unmatched_gao_cra2.to_csv("unmatched_gao_cra2.csv", index=False)

In [18]:
# combine dfs and remove duplicates
# unmatched_fr_tracking3 = pd.concat([unmatched_fr_tracking1, unmatched_fr_tracking2]).drop_duplicates(subset=["citation"]).reset_index(drop=True)
# unmatched_fr_tracking3.info()
# unmatched_fr_tracking3.to_csv("unmatched_fr_tracking3.csv", index=False)

In [19]:
# combine dfs and remove duplicates
# unmatched_gao_cra3 = pd.concat([unmatched_gao_cra1, unmatched_gao_cra2]).drop_duplicates(subset=["fed_reg_number"]).reset_index(drop=True)
# unmatched_gao_cra3.info()
# unmatched_gao_cra3.to_csv("unmatched_gao_cra3.csv", index=False)