In [106]:
# import libraries
import pandas as pd
import numpy as np  
from IPython.display import display
import json
import re

In [107]:
# load fr_tracking csv
csv1 = 'fr_tracking_new.csv'

fr_tracking0 = pd.read_csv(csv1, encoding="ISO-8859-1", sep=None, engine="python", header=0)
display(fr_tracking0.head(5))

,publication_date,effective_on,department,agency,independent_reg_agency,title,abstract,action,citation,document_number,regulation_id_number,docket_number,significant,econ_significant,3(f)(1) significant,Major,html_url,Notes
0,1/21/21,4/22/21,Transportation Department,Federal Aviation Administration,0,Amendment of Class D and Class E Airspace and ...,This action amends the Class D and Class E air...,Final rule.,86 FR 6243,2021-01019,2120-AA66,FAA-2020-0871,NaN,NaN,NaN,NaN,https://www.federalregister.gov/documents/2021...,NaN
1,1/21/21,4/22/21,Transportation Department,Federal Aviation Administration,0,Amendment of Class D and Class E Airspace and ...,This action amends the Class D and Class E air...,Final rule.,86 FR 6244,2021-01020,2120-AA66,FAA-2020-0759,NaN,NaN,NaN,NaN,https://www.federalregister.gov/documents/2021...,NaN
2,1/21/21,2/22/21,Homeland Security Department,Coast Guard,0,"Safety Zone; Tanapag Harbor, Saipan, CNMI",The Coast Guard is establishing a annually rec...,Final rule.,86 FR 6247,2021-01084,1625-AA00,USCG-2020-0459,NaN,NaN,NaN,NaN,https://www.federalregister.gov/documents/2021...,NaN
3,1/21/21,2/22/21,Health and Human Services Department,Public Health Service,0,National Vaccine Injury Compensation Program: ...,The Secretary finalizes the proposed rule to a...,Final rule.,86 FR 6249,2021-01211,0906-AB24,HHS-OS-2022-0008,NaN,NaN,NaN,NaN,https://www.federalregister.gov/documents/2021...,NaN
4,1/22/21,4/1/21,Federal Deposit Insurance Corporation,NaN,1,Unsafe and Unsound Banking Practices: Brokered...,The FDIC is finalizing revisions to its regula...,Final rule.,86 FR 6742,2020-28196,3064-AE94,NaN,NaN,NaN,NaN,NaN,https://www.federalregister.gov/documents/2021...,NaN

In [108]:
# load gao_cra json
json_file = "gao_cra.json"

with open(json_file, "r", encoding="ISO-8859-1") as f:
    data = json.load(f) 
    
gao_cra0 = pd.DataFrame(data["results"])

display(gao_cra0.head(5))
gao_cra0.to_csv("gao_cra.csv", index=False)

,url,title,agency,subagency,type,description,priority,date_published_in_federal_register,effective,received,control_number,fed_reg_number,identifier,major_rule_report
0,https://www.gao.gov/fedrules/210969,Federal Rules: Energy Conservation Program: En...,Department of Energy,Department of Energy,Major,ENERGY CONSERVATION PROGRAM: ENERGY CONSERVATI...,Significant/Substantive,2025-01-21T13:00:00Z,2025-03-24T13:00:00Z,2025-01-30T13:00:00Z,210969,90 FR 7464,1904-AD82,https://www.gao.gov/products/b-337132
1,https://www.gao.gov/fedrules/210873,Federal Rules: Minimum Standards For Driver?S ...,Department of Homeland Security,Transportation Security Administration,Major,MINIMUM STANDARDS FOR DRIVER?S LICENSES AND ID...,Significant/Substantive,2025-01-14T13:00:00Z,2025-01-14T13:00:00Z,2025-01-22T13:00:00Z,210873,90 FR 3472,1652-AA77,https://www.gao.gov/products/b-337041
2,https://www.gao.gov/fedrules/210892,Federal Rules: Certificates Of Compliance | U....,Independent Government Entities,Consumer Product Safety Commission,Major,CERTIFICATES OF COMPLIANCE,Significant/Substantive,2025-01-08T13:00:00Z,2026-07-08T13:00:00Z,2025-01-21T13:00:00Z,210892,90 FR 1800,NaN,https://www.gao.gov/products/b-337029
3,https://www.gao.gov/fedrules/210874,"Federal Rules: Post-9/11 Improvements, Fry Sch...",Department of Veterans Affairs,Department of Veterans Affairs,Major,"POST-9/11 IMPROVEMENTS, FRY SCHOLARSHIP, AND I...",Significant/Substantive,2025-01-16T13:00:00Z,2025-03-17T13:00:00Z,2025-01-17T13:00:00Z,210874,90 FR 5324,2900-AQ88,https://www.gao.gov/products/b-337024
4,https://www.gao.gov/fedrules/210824,Federal Rules: Securing The Information And Co...,Department of Commerce,Bureau of Industry and Security,Major,SECURING THE INFORMATION AND COMMUNICATIONS TE...,Significant/Substantive,2025-01-16T13:00:00Z,2025-03-17T13:00:00Z,2025-01-16T13:00:00Z,210824,90 FR 5360,0694-AJ56,https://www.gao.gov/products/b-337023

In [109]:
# fr_tracking df info
print("fr_tracking0 info:")
fr_tracking0.info()

fr_tracking0 info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12966 entries, 0 to 12965
Data columns (total 18 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   publication_date        12966 non-null  object
 1   effective_on            11598 non-null  object
 2   department              12952 non-null  object
 3   agency                  8342 non-null   object
 4   independent_reg_agency  12966 non-null  int64
 5   title                   12966 non-null  object
 6   abstract                12794 non-null  object
 7   action                  12790 non-null  object
 8   citation                12966 non-null  object
 9   document_number         12966 non-null  object
 10  regulation_id_number    7703 non-null   object
 11  docket_number           10696 non-null  object
 12  significant             0 non-null      float64
 13  econ_significant        0 non-null      float64
 14  3(f)(1) significant     0 non-null      float64
 15  Major                   0 non-null      float64
 16  html_url                12966 non-null  object
 17  Notes                   0 non-null      float64
dtypes: float64(5), int64(1), object(12)
memory usage: 1.8+ MB

In [110]:
# gao_cra df info
print("gao_cra0 info:")
gao_cra0.info()

gao_cra0 info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7399 entries, 0 to 7398
Data columns (total 14 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   url                                 7399 non-null   object
 1   title                               7399 non-null   object
 2   agency                              7399 non-null   object
 3   subagency                           7378 non-null   object
 4   type                                7399 non-null   object
 5   description                         7399 non-null   object
 6   priority                            7260 non-null   object
 7   date_published_in_federal_register  7184 non-null   object
 8   effective                           7292 non-null   object
 9   received                            7399 non-null   object
 10  control_number                      7399 non-null   object
 11  fed_reg_number                      7357 non-null   object
 12  identifier                          5311 non-null   object
 13  major_rule_report                   459 non-null    object
dtypes: object(14)
memory usage: 809.4+ KB

In [111]:
# fr_tracking data manipulation

# change date columns to YYYY-MM-DD format
fr_date_cols = ["publication_date", "effective_on"]
fr_tracking0[fr_date_cols] = fr_tracking0[fr_date_cols].apply(pd.to_datetime, errors="coerce", format="mixed")

# change id columns to string
fr_id_cols = ["citation", "regulation_id_number"]
fr_tracking0[fr_id_cols] = fr_tracking0[fr_id_cols].astype("string")

# add df id column
fr_tracking0["in_fr_df"] = 1

display(fr_tracking0.head(2))

,publication_date,effective_on,department,agency,independent_reg_agency,title,abstract,action,citation,document_number,regulation_id_number,docket_number,significant,econ_significant,3(f)(1) significant,Major,html_url,Notes,in_fr_df
0,2021-01-21,2021-04-22,Transportation Department,Federal Aviation Administration,0,Amendment of Class D and Class E Airspace and ...,This action amends the Class D and Class E air...,Final rule.,86 FR 6243,2021-01019,2120-AA66,FAA-2020-0871,NaN,NaN,NaN,NaN,https://www.federalregister.gov/documents/2021...,NaN,1
1,2021-01-21,2021-04-22,Transportation Department,Federal Aviation Administration,0,Amendment of Class D and Class E Airspace and ...,This action amends the Class D and Class E air...,Final rule.,86 FR 6244,2021-01020,2120-AA66,FAA-2020-0759,NaN,NaN,NaN,NaN,https://www.federalregister.gov/documents/2021...,NaN,1

In [112]:
print("fr_tracking0 info:")
fr_tracking0.info()

fr_tracking0 info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12966 entries, 0 to 12965
Data columns (total 19 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   publication_date        12966 non-null  datetime64[ns]
 1   effective_on            11598 non-null  datetime64[ns]
 2   department              12952 non-null  object
 3   agency                  8342 non-null   object
 4   independent_reg_agency  12966 non-null  int64
 5   title                   12966 non-null  object
 6   abstract                12794 non-null  object
 7   action                  12790 non-null  object
 8   citation                12966 non-null  string
 9   document_number         12966 non-null  object
 10  regulation_id_number    7703 non-null   string
 11  docket_number           10696 non-null  object
 12  significant             0 non-null      float64
 13  econ_significant        0 non-null      float64
 14  3(f)(1) significant     0 non-null      float64
 15  Major                   0 non-null      float64
 16  html_url                12966 non-null  object
 17  Notes                   0 non-null      float64
 18  in_fr_df                12966 non-null  int64
dtypes: datetime64[ns](2), float64(5), int64(2), object(8), string(2)
memory usage: 1.9+ MB

In [113]:
# gao_cra data manipulation

# change date columns to YYYY-MM-DD format
gao_date_cols = ["date_published_in_federal_register", "effective", "received"]
gao_cra0[gao_date_cols] = gao_cra0[gao_date_cols].apply(pd.to_datetime, errors="coerce")
gao_cra0[gao_date_cols] = gao_cra0[gao_date_cols].apply(lambda x: x.dt.tz_localize(None).dt.normalize())

# change id columns to string
gao_id_cols = ["fed_reg_number", "identifier"]
gao_cra0[gao_id_cols] = gao_cra0[gao_id_cols].astype("string")

# add df id column
gao_cra0["in_gao_df"] = 1

display(gao_cra0.head(2))

,url,title,agency,subagency,type,description,priority,date_published_in_federal_register,effective,received,control_number,fed_reg_number,identifier,major_rule_report,in_gao_df
0,https://www.gao.gov/fedrules/210969,Federal Rules: Energy Conservation Program: En...,Department of Energy,Department of Energy,Major,ENERGY CONSERVATION PROGRAM: ENERGY CONSERVATI...,Significant/Substantive,2025-01-21,2025-03-24,2025-01-30,210969,90 FR 7464,1904-AD82,https://www.gao.gov/products/b-337132,1
1,https://www.gao.gov/fedrules/210873,Federal Rules: Minimum Standards For Driver?S ...,Department of Homeland Security,Transportation Security Administration,Major,MINIMUM STANDARDS FOR DRIVER?S LICENSES AND ID...,Significant/Substantive,2025-01-14,2025-01-14,2025-01-22,210873,90 FR 3472,1652-AA77,https://www.gao.gov/products/b-337041,1

In [114]:
print("gao_cra0 info:")
gao_cra0.info()

gao_cra0 info:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7399 entries, 0 to 7398
Data columns (total 15 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   url                                 7399 non-null   object
 1   title                               7399 non-null   object
 2   agency                              7399 non-null   object
 3   subagency                           7378 non-null   object
 4   type                                7399 non-null   object
 5   description                         7399 non-null   object
 6   priority                            7260 non-null   object
 7   date_published_in_federal_register  7031 non-null   datetime64[ns]
 8   effective                           7253 non-null   datetime64[ns]
 9   received                            7399 non-null   datetime64[ns]
 10  control_number                      7399 non-null   object
 11  fed_reg_number                      7357 non-null   string
 12  identifier                          5311 non-null   string
 13  major_rule_report                   459 non-null    object
 14  in_gao_df                           7399 non-null   int64
dtypes: datetime64[ns](3), int64(1), object(9), string(2)
memory usage: 867.2+ KB

In [115]:
# fr_tracking data cleaning

# drop rows with "N/A" or no values in the citation column
#fr_tracking_all_fr_cit = fr_tracking0.replace("N/A", np.nan).dropna(subset=["citation"])

# only keep rows that contain "FR" plus numbers (eleminates abnormalities)
#fr_tracking_all_fr_cit = fr_tracking_all_fr_cit[fr_tracking_all_fr_cit["citation"].str.fullmatch(r".*\bFR\b.*", na=False)]

In [116]:
# gao_cra data cleaning

# drop rows with "N/A" or no values in the fed_reg_number column
#gao_cra_all_fr_cit = gao_cra0.replace("N/A", np.nan).dropna(subset=["fed_reg_number"])

# only keep rows that contain "FR" plus numbers (eleminates abnormalities)
#gao_cra_all_fr_cit = gao_cra_all_fr_cit[gao_cra_all_fr_cit["fed_reg_number"].str.fullmatch(r".*\bFR\b.*", na=False)]

In [117]:
# fr_tracking anti-join on citation/fed_reg_number
# fr_tracking_unmatched_on_fr_cit = fr_tracking_all_fr_cit[~fr_tracking_all_fr_cit["citation"].isin(gao_cra_all_fr_cit["fed_reg_number"])]
# fr_tracking_unmatched_on_fr_cit.info()
# fr_tracking_unmatched_on_fr_cit.to_csv("fr_tracking_unmatched_on_fr_cit.csv", index=False)

In [118]:
# gao_cra anti-join on citation/fed_reg_number
# gao_cra_unmatched_on_fr_cit = gao_cra_all_fr_cit[~gao_cra_all_fr_cit["fed_reg_number"].isin(fr_tracking_all_fr_cit["citation"])]
# gao_cra_unmatched_on_fr_cit.info()
# gao_cra_unmatched_on_fr_cit.to_csv("gao_cra_unmatched_on_fr_cit.csv", index=False)

In [119]:
# fr_tracking data cleaning

# drop rows with "." or no values in the regulation_id_number column
fr_tracking_all_id_date = fr_tracking0.replace(".", np.nan).dropna(subset=["regulation_id_number"])

# drop rows containing "Docket No", "Doc. No.", or "FR"
#fr_tracking_all_id_date = fr_tracking_all_id_date[~fr_tracking_all_id_date["regulation_id_number"].str.contains(r"Docket No|Doc\. No\.|FR", na=False, regex=True)]

# convert regulation_id_number column to a list of lists (so groups of RINs can be searched for individual RINs)
fr_tracking_all_id_date["regulation_id_number"] = fr_tracking_all_id_date["regulation_id_number"].str.split(r"\s*;\s*")

#fr_tracking_all_id_date.to_csv("fr_tracking_all_id_date.csv", index=False)

In [120]:
# gao_cra data cleaning

# drop rows with "N/A" or no values in the identifier and date_published_in_federal_register columns
gao_cra_all_id_date = gao_cra0.replace("N/A", np.nan).dropna(subset=["identifier", "date_published_in_federal_register"])

# replace all "?" values in the identifier column with "-"
gao_cra_all_id_date["identifier"] = gao_cra_all_id_date["identifier"].str.replace("?", "-", regex=False)

# replace all "ZRIN ", "Z-RIN ", "RIN ", "OMB ", "AND " in identifier column with ""
gao_cra_all_id_date["identifier"] = gao_cra_all_id_date["identifier"].str.replace(r"\b(ZRIN |Z-RIN |RIN |OMB |AND )", "", regex=True)

# convert identifier column to a list of lists (converting "&" and "," to spaces)
gao_cra_all_id_date["identifier"] = gao_cra_all_id_date["identifier"].apply(lambda x: re.split(r"\s*[,&]\s*", x))

# rename columns that will be used for anti-joining to match the corresponding FR tracking column names
gao_cra_all_id_date.rename(columns={
    "date_published_in_federal_register": "publication_date",
    "identifier": "regulation_id_number",
}, inplace=True)

#gao_cra_all_id_date.to_csv("gao_cra_all_id_date.csv", index=False)

In [121]:

# ensure regulation_id_number are lists
fr_tracking_all_id_date["regulation_id_number"] = fr_tracking_all_id_date["regulation_id_number"].apply(lambda x: x if isinstance(x, list) else [x])
gao_cra_all_id_date["regulation_id_number"] = gao_cra_all_id_date["regulation_id_number"].apply(lambda x: x if isinstance(x, list) else [x])

# explode regulation_id_number into separate rows (essentially making a long df based off of all the RIN/publication date combos)
fr_exploded = fr_tracking_all_id_date.explode("regulation_id_number")
gao_exploded = gao_cra_all_id_date.explode("regulation_id_number")

# merge on both "publication_date" and "regulation_id_number"
merged_df = fr_exploded.merge(
    gao_exploded,
    on=["publication_date", "regulation_id_number"],
    how="left",  # leeps all fr_exploded rows, adds matching gao_exploded rows
    suffixes=("_fr", "_gao")
)

# re-group regulation_id_number back into lists while keeping all other columns
grouping_columns = [col for col in merged_df.columns if col not in ["regulation_id_number"]]
merged_df = merged_df.groupby(grouping_columns, dropna=False)["regulation_id_number"].apply(list).reset_index()

# convert the in_gao_df column to int and add 0s in the place of NaNs
merged_df["in_gao_df"] = merged_df["in_gao_df"].fillna(0).astype(int)

# export
merged_df.to_csv("merged_df.csv", index=False)

In [122]:

# create new df with only the rows where in_gao_df = 0
filtered_df1 = merged_df[merged_df["in_gao_df"] == 0]

# export
filtered_df1.to_csv("filtered_df1.csv", index=False)